# Generated by Django 3.2.7 on 2021-10-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='color_hex',
            new_name='color',
        ),
    ]
